import * as React from 'react';
import { Metadata } from 'next';
import { Inter, Kumbh_Sans } from 'next/font/google';
import './globals.css';
import { NextUIProvider } from '@nextui-org/react';
import NavbarComponent from './components/Navbar';

const kumbhSans = Kumbh_Sans({
	subsets: ['latin'],
	weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
	variable: '--kumbh-sans',
});
const inter = Inter({ subsets: ['latin'], display: 'swap', variable: '--inter' });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${kumbhSans.className} ${inter.variable}`} suppressHydrationWarning={true}>
				<NextUIProvider>
					<main className='w-full'>
						<NavbarComponent />
						{children}
					</main>
				</NextUIProvider>
			</body>
		</html>
	);
}
